

#[derive(Debug, Clone, Copy)]
pub enum Op<'a> {
    PushStr(&'a str),
    PushChar(char),
    PushNumber(i64),
    PushRefLocal(usize),
    PushRefGlobal(usize),
    PushBool(bool),
    PushVoid,
    Pop,
    Dup,
    DupTarget(usize),
    Swap,
    PushFn(usize),
    MakeRange(bool),
    StoreLocal(usize),
    LoadLocal(usize),
    LoadGlobal(usize),
    StoreGlobal(usize),
    CallFunc(usize),
    JumpIfFalse(usize),
    Jump(usize),
    JumpIfTrue(usize),
    ArifmOr,
    ArifmAnd,
    Not,
    Plus,
    Sub,
    Mult,
    Pow,
    Div,
    Mod,
    MakeSet(usize),
    MakeIter,
    IterNext(usize),
    LoadIndex(usize),
    StoreIndex(usize),
    Equal,
    Greater,
    MakeOk,
    MakeErr,
    MakeSome,
    None,
    SafeUnwR(usize),
    SafeUnwL(usize),
    Less,
    GreaterEq,
    LessEq,
    Return,
}
