

#[derive(Debug, Clone, Copy)]
pub enum Op<'a> {
    PushStr(&'a str),
    PushChar(char),
    PushNumber(i64),
    PushRef(usize),
    PushBool(bool),
    PushVoid,
    Pop,
    Dup,
    DupTarget(usize),
    Swap,
    PushFn(usize),
    MakeRange(bool),
    StoreLocal(usize),
    LoadLocal(usize),
    LoadGlobal(usize),
    StoreGlobal(usize),
    CallFunc(usize),
    JumpIfFalse(usize),
    Jump(usize),
    JumpIfTrue(usize),
    ArifmOr,
    ArifmAnd,
    Not,
    Plus,
    Sub,
    Mult,
    Pow,
    Div,
    MakeSet(usize),
    MakeIter,
    IterNext(usize),
    LoadIndex(usize),
    StoreIndex(usize),
    Equal,
    Greater,
    Less,
    GreaterEq,
    LessEq,
    Return,
}
