use crate::types::Type;

#[derive(Debug, Clone)]
pub enum Op<'a> {
    PushStr(&'a str),
    PushChar(char),
    PushNumber(i64),
    PushFLoat(f64),
    PushRefGlobal(usize),
    PushBool(bool),
    PushVoid,
    Pop,
    Dup,
    MakeTuple(usize),   
    UnpackTuple(usize),
    DupTarget(usize),
    PushFn(usize),
    MakeRange(bool),
    LoadGlobal(usize),
    StoreGlobal(usize),
    CallFunc(usize),
    JumpIfFalse(usize),
    Jump(usize),
    JumpIfTrue(usize),
    PushRefLocal(usize, usize),
    StoreLocal(usize, usize),  
    LoadLocal(usize, usize),   
    ArifmOr,
    ArifmAnd,
    Not,
    Plus,
    Sub,
    Mult,
    Pow,
    Div,
    Mod,
    ExpectType(Type),
    MakeSet(usize),
    MakeIter,
    IterNext(usize),
    LoadIndex(usize),
    StoreIndex(usize),
    Equal,
    NotEqual,
    Greater,
    MakeOk,
    MakeErr,
    MakeSome,
    None,
    SafeUnwR(usize),
    SafeUnwL(usize),
    Less,
    GreaterEq,
    LessEq,
    Return,
}
